"""Write a CI workflow that runs this tool.

The generated workflow is generic. A consumer such as FetchCord chooses an
emit format and an output directory. No Discord token is written.
"""

from __future__ import annotations

from pathlib import Path

import yaml

DEFAULT_APPKIT_REPO = "BlivionIaG/discord-appkit"
WORKFLOW_PATH = Path(".github/workflows/discord-assets.yml")
CONFIG_PATH = Path("discord-appkit.yml")

WORKFLOW = """name: discord-assets

# Written by discord-appkit. Syncs declared Discord catalogs.
# Does not upload assets or read a portal token.
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: checkout discord-appkit
        uses: actions/checkout@v4
        with:
          repository: __APPKIT_REPO__
          ref: __APPKIT_REF__
          path: .appkit

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: sync catalogs
        run: |
          pip install -e .appkit
          appkit emit --lock .appkit/state/ids.lock.json --format __FORMAT__ --out __OUT__ --merge

      - name: open pull request if catalogs changed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name "discord-appkit"
          git config user.email "appkit@users.noreply.github.com"
          git add __OUT__
          if git diff --cached --quiet; then
            echo "catalogs already match"
            exit 0
          fi
          branch="appkit/sync-${GITHUB_RUN_ID}"
          git checkout -b "$branch"
          git commit -m "chore: sync Discord catalogs"
          git push origin "HEAD:refs/heads/${branch}"
          gh pr create --base "${GITHUB_REF_NAME}" --head "$branch" \\
            --title "chore: sync Discord catalogs" \\
            --body "Generated by discord-appkit. No tokens."
"""


def render_config(fmt: str, out: str, appkit_repo: str, appkit_ref: str) -> str:
    payload = {
        "version": 1,
        "format": fmt,
        "out": out,
        "appkit": {"repo": appkit_repo, "ref": appkit_ref},
    }
    return "# Written by discord-appkit. No secrets.\n" + yaml.safe_dump(payload, sort_keys=False)


def render_workflow(fmt: str, out: str, appkit_repo: str, appkit_ref: str) -> str:
    text = (
        WORKFLOW.replace("__APPKIT_REPO__", appkit_repo)
        .replace("__APPKIT_REF__", appkit_ref)
        .replace("__FORMAT__", fmt)
        .replace("__OUT__", out)
    )
    if "secrets.DISCORD_USER_TOKEN" in text:
        raise ValueError("generated CI must not reference a Discord token")
    return text


def init_ci(
    checkout: Path,
    fmt: str,
    out: str,
    appkit_repo: str = DEFAULT_APPKIT_REPO,
    appkit_ref: str = "master",
) -> list[Path]:
    if not checkout.is_dir():
        raise FileNotFoundError(f"not a directory: {checkout}")
    written: list[Path] = []

    config = checkout / CONFIG_PATH
    config.write_text(render_config(fmt, out, appkit_repo, appkit_ref), encoding="utf-8")
    written.append(config)

    workflow = checkout / WORKFLOW_PATH
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(render_workflow(fmt, out, appkit_repo, appkit_ref), encoding="utf-8")
    written.append(workflow)
    return written
