apiVersion: appkit.discord/v1
kind: DiscordApplication
metadata:
  name: fetchcord-distro-arch
  category: distro
  keys:
    - arch
spec:
  description: FetchCord Rich Presence — Arch Linux
  existingId: "740476198437650473"
  flags:
    richPresence: true
  assets:
    - name: arch
      type: rich
      file: assets/distro/arch.png
